### ISSUE TITLE
bash: line 4: /sbin/ifdown: No such file or directory

### ISSUE THREAD

**Issue by leslie-wang** [haggaie/rdma-experiment#1]
It is reported at https://github.com/cilium/cilium/issues/1918. Seems like ifupdown need be installed at provision script.

Ubuntu: '20180210.0.0
Virtualbox: 5.2.2 r119230 (Qt5.6.3)
MacOS: 10.13.3 (17D47)

**Comment by haggaie** [comment]
I think the latest version of vagrant should fix this issue.

**Comment by leslie-wang** [comment]
You are right. After upgrading to vagrant 2.0.3, the issue has gone.
