### ISSUE TITLE
validate send failed

### ISSUE THREAD

**Issue by leslie-wang** [haggaie/rdma-experiment#2]
Thanks for making the great environment to ease development.

I'm trying to build and run client/server application, but got below failure. Do you have any idea on why it failed?
```
vagrant@ubuntu-bionic:/vagrant/src/build$ ./rdma_client -s 192.168.0.11
rdma_client: start
validate send failed
rdma_post_send: Unknown error -22
rdma_client: end -1

vagrant@ubuntu-bionic:/vagrant/src/build$ sudo rxe_cfg status
  Name    Link  Driver  Speed  NMTU  IPv4_addr  RDEV  RMTU
  enp0s3  yes   e1000
  enp0s8  yes   e1000                           rxe0  1024  (3)
```

ibv_rc_pingpong works fine btw client and server

**Comment by haggaie** [comment]
Thanks for reporting this. I believe there is an issue with inline transmission and the RXE driver. I disabled it by default in commit 80bdc39d07766f331cacfbdddb419e2bbe56a33a and it seems to work with inline send disabled.
